[package]
name = "faces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.30.1"
tensorflow = "0.17.0"
image = "0.24.0"
lazy_static = "1.4.0"